#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TestLec3.Resource", IsApplication=true)]

namespace TestLec3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int scaled = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int unscaled = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050018
			public const int absoluteLayoutButton = 2131034136;
			
			// aapt resource value: 0x7f050002
			public const int callButton = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int cameraButton = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int fragment_change_button = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int fragment_container = 2131034112;
			
			// aapt resource value: 0x7f05001c
			public const int fragmentsButton = 2131034140;
			
			// aapt resource value: 0x7f050005
			public const int imageView = 2131034117;
			
			// aapt resource value: 0x7f050019
			public const int intentsButton = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int layoutsButton = 2131034138;
			
			// aapt resource value: 0x7f050016
			public const int linearLayoutButton = 2131034134;
			
			// aapt resource value: 0x7f050004
			public const int newActivityButton = 2131034116;
			
			// aapt resource value: 0x7f050017
			public const int relativeLayoutButton = 2131034135;
			
			// aapt resource value: 0x7f05001b
			public const int resourcesButton = 2131034139;
			
			// aapt resource value: 0x7f05000b
			public const int strut = 2131034123;
			
			// aapt resource value: 0x7f05001d
			public const int text = 2131034141;
			
			// aapt resource value: 0x7f05000c
			public const int text1 = 2131034124;
			
			// aapt resource value: 0x7f050015
			public const int text10 = 2131034133;
			
			// aapt resource value: 0x7f05000d
			public const int text2 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int text3 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int text4 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int text5 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int text6 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int text7 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int text8 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int text9 = 2131034132;
			
			// aapt resource value: 0x7f050006
			public const int textView1 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int textView2 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int textView3 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int textView4 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int textView5 = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_fragments = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_intent = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_layout_absolute = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_layout_linear = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_layout_relative = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_layouts = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int activity_main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int activity_resources = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int activity_to_start = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int fragment_blue = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int fragment_green = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int fragment_red = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
